services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Migrify\Psr4Switcher\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/*'
            - '../src/ValueObject/*'

    Symfony\Component\Filesystem\Filesystem: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
    Symplify\SmartFileSystem\FileSystemGuard: null
